set autoread
set number
set hlsearch
set incsearch 
set autoindent
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4 
set ruler
set undolevels=1000
set backspace=indent,eol,start
syntax on
